# Generated by Django 6.0.4 on 2026-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_medicine_ordered_at_medicine_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified & Available'), ('rejected', 'Rejected'), ('sold', 'Sold')], default='pending', max_length=20),
        ),
    ]
