# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_medicine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_account',
            field=models.BooleanField(default=False),
        ),
    ]
