# Generated by Django 6.0.6 on 2026-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_medicine_category_medicine_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(blank=True, upload_to='medicines/%Y/%m/'),
        ),
    ]
