# Generated by Django 6.0.6 on 2026-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_medicine_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='qr_code_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
