# Generated by Django 6.0.6 on 2026-07-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_medicine_qr_code_id_medicine_qr_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pickup_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
