# Generated by Django 6.0.6 on 2026-07-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_medicine_otp_generated_at_medicine_pickup_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='donation_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='package_type',
            field=models.CharField(choices=[('strip', 'Strip'), ('bottle', 'Bottle'), ('box', 'Box'), ('tube', 'Tube'), ('injection', 'Injection'), ('other', 'Other')], default='strip', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pickup_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_condition',
            field=models.CharField(choices=[('room_temperature', 'Room Temperature'), ('refrigerated', 'Refrigerated'), ('cool_dry', 'Cool & Dry Place'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
