# Generated by Django 6.0.6 on 2026-07-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_medicine_otp_generated_at_medicine_pickup_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
