# Generated by Django 6.0.6 on 2026-07-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_medicine_area_medicine_district_and_more'),
        ('myapp', '0010_user_nid'),
    ]

    operations = [
    ]
